// Maps country names (as returned by the data source) to emoji flags.
// Falls back to a soccer ball when a country isn't in the map.
const COUNTRY_FLAGS: Record<string, string> = {
  Algeria: '🇩🇿',
  Argentina: '🇦🇷',
  Australia: '🇦🇺',
  Austria: '🇦🇹',
  Belgium: '🇧🇪',
  Bolivia: '🇧🇴',
  'Bosnia-Herzegovina': '🇧🇦',
  'Bosnia and Herzegovina': '🇧🇦',
  Brazil: '🇧🇷',
  Cameroon: '🇨🇲',
  Canada: '🇨🇦',
  'Cape Verde': '🇨🇻',
  Chile: '🇨🇱',
  Colombia: '🇨🇴',
  'Congo DR': '🇨🇩',
  'DR Congo': '🇨🇩',
  'Costa Rica': '🇨🇷',
  Croatia: '🇭🇷',
  'Curaçao': '🇨🇼',
  Curacao: '🇨🇼',
  'Czech Republic': '🇨🇿',
  Czechia: '🇨🇿',
  Denmark: '🇩🇰',
  Ecuador: '🇪🇨',
  Egypt: '🇪🇬',
  England: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  France: '🇫🇷',
  Germany: '🇩🇪',
  Ghana: '🇬🇭',
  Haiti: '🇭🇹',
  Iran: '🇮🇷',
  Iraq: '🇮🇶',
  'Ivory Coast': '🇨🇮',
  Jordan: '🇯🇴',
  Japan: '🇯🇵',
  'South Korea': '🇰🇷',
  'Korea Republic': '🇰🇷',
  Korea: '🇰🇷',
  Mexico: '🇲🇽',
  Morocco: '🇲🇦',
  Netherlands: '🇳🇱',
  'New Zealand': '🇳🇿',
  Nigeria: '🇳🇬',
  Norway: '🇳🇴',
  Panama: '🇵🇦',
  Paraguay: '🇵🇾',
  Peru: '🇵🇪',
  Poland: '🇵🇱',
  Portugal: '🇵🇹',
  Qatar: '🇶🇦',
  'Saudi Arabia': '🇸🇦',
  Scotland: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  Senegal: '🇸🇳',
  Serbia: '🇷🇸',
  'South Africa': '🇿🇦',
  Spain: '🇪🇸',
  Sweden: '🇸🇪',
  Switzerland: '🇨🇭',
  Tunisia: '🇹🇳',
  Turkey: '🇹🇷',
  'Türkiye': '🇹🇷',
  'United States': '🇺🇸',
  USA: '🇺🇸',
  Uruguay: '🇺🇾',
  Uzbekistan: '🇺🇿',
  Wales: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
};

export const countryFlag = (name: string | null | undefined): string => {
  if (!name) return '⚽';
  return COUNTRY_FLAGS[name.trim()] ?? '⚽';
};
